---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: rhsummit-shop-demo-scc-storeuser
  labels:
    backstage.io/kubernetes-id: rhsummit-shop-demo
    app.kubernetes.io/name: rhsummit-shop-demo
    rht-gitops.com/janus-argocd: rhsummit-shop-demo
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:rh-demo:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: rhsummit-shop-demo-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: rhsummit-shop-demo
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:rh-demo:storeuseradmin-sa
